esphome:
  name: aire_acondicionat
  platform: ESP8266
  board: esp01_1m
  includes:
    - Haier.h

logger:
  level: DEBUG
  baud_rate: 0 #Important. You can't use serial port
  
wifi:
  ssid: "xxx"
  password: "xxx"

# Enable Home Assistant API
api:

ota:


climate:
  - platform: custom
    lambda: |-
      auto haier = new Haier();
      App.register_component(haier);
      return {haier};
    climates:
      - name: "Haier"